---
grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.jencub.xyz
    path: /
  metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
